### ISSUE TITLE
Platform Stability Checklist

### ISSUE THREAD

**Issue by elcharitas** [ngyn-rs/ngyn#89]
- [x] - Fix broken platform macro
- [x] - Fix broken compat of Vercel platform
- [x] - Fix Controller Generics
- [x] - Update examples
